name: 'Build and Test'
inputs:
  ref:
    type: string
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - run: pytest --verbose
    - name: Install build tools
      run: |
        choco install nsis upx -y
    - name: Build package
      run: |
        tools\compile.bat
    - name: Test Installer
      run: |
        tools\test-installer.ps1 -confirm y
