name: Build and Test

on:
  push:
    paths:
      - src/**
      - tools/**
      - test/**
      - requirements*.txt
      - .github/workflows/build-and-test.yml
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      gitRef:
        description: The git ref to build against
        required: true
        type: string
      doArtifact:
        description: Publish an artifact
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      gitRef:
        description: The git ref to build against
        required: true
        type: string
      doArtifact:
        description: Publish an artifact
        required: false
        default: false
        type: boolean


jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gitRef }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Python Tests
        run: pytest --verbose
      - name: Install build tools
        run: |
          choco install nsis upx -y
      - name: Build package
        run: |
          tools\compile.bat
      - name: Test Installer
        run: |
          tools\test-installer.ps1 -confirm y
      - name: Publish artifact
        if: ${{ inputs.doArtifact }}
        uses: actions/upload-artifact@v3
        with:
          name: RWP-dist
          path: dist/
