name: Release on tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: The tag we need to check out
        required: true

jobs:
  getversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.pkgVersion }}
    steps:
      - name: Get version
        id: get_version
        run: |
          version=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]
          then
            version="${{ github.event.inputs.version }}"
          else
            version="$GITHUB_REF_NAME"
          fi
          echo "pkgVersion=$version" >> $GITHUB_OUTPUT
          echo "Version: $version"
  publish:
    runs-on: windows-latest
    needs: getversion
    environment: build
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{needs.getversion.outputs.version}}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Choco install build tools
        run: |
          choco install nsis upx -y
      - name: Build package
        run: |
          tools\compile.bat
      - name: Push to chocolatey
        env:
          PKGVERSION: ${{needs.getversion.outputs.version}}
        run: |
          choco push "dist/restorewindowpos.$env:PKGVERSION.nupkg" --source "https://push.chocolatey.org/" -k "${{secrets.CHOCO_API_KEY}}"
