name: Release on tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: The tag we need to check out
        required: true

jobs:
  getversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.pkgVersion }}
    steps:
      - name: Get version
        id: get_version
        run: |
          version=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]
          then
            version="${{ github.event.inputs.version }}"
          else
            version="$GITHUB_REF_NAME"
          fi
          echo "pkgVersion=$version" >> $GITHUB_OUTPUT
          echo "Version: $version"
  publish:
    runs-on: windows-latest
    needs: getversion
    environment: build
    steps:
      - uses: ./.github/actions/build_and_test.yml
        with:
          ref: ${{needs.getversion.outputs.version}}
      - name: Get installer checksum
        id: get_installer_checksum
        run: |
          echo "pkgChecksum=$(Get-FileHash -Path .\RestoreWindowPos_install.exe -Algorithm sha256).Hash" >> $env:GITHUB_OUTPUT
      - name: Draft GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: "RestoreWindowPos_install.exe SHA256 Checksum: `${{steps.get_installer_checksum.outputs.pkgChecksum}}`"
          draft: true
          files: "dist/RestoreWindowPos_install.exe"
          name: "RestoreWindowPos v${{needs.getversion.outputs.version}}"
          tag_name: ${{needs.getversion.outputs.version}}
      - name: Push to chocolatey
        env:
          PKGVERSION: ${{needs.getversion.outputs.version}}
        run: |
          choco push "dist/restorewindowpos.$env:PKGVERSION.nupkg" --source "https://push.chocolatey.org/" -k "${{secrets.CHOCO_API_KEY}}"
