name: Tests

on:
  push:
    paths:
      src/*
      .github/*
      test/*
      tools/*
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: ./.github/actions/build_and_test.yml
